version: '{build}'
pull_requests:
  do_not_increment_build_number: true
environment:
  ProjectVersion: build$(APPVEYOR_BUILD_VERSION)
  matrix:
    - PYTHON: C:\Python38-x64
install:
  - cmd: pip install -r requirements.txt --upgrade
build_script:
  - cmd: setup.py build_exe
artifacts:
  - path: build\exe.win-amd64-3.8\
    name: Berserker_Multiworld_{branch}_{version}.zip
